
ALTER TABLE Users ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE Campaigns ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE Campaigns ALTER COLUMN creator TYPE VARCHAR(100);
ALTER TABLE Donations ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE Donations ALTER COLUMN campaignId TYPE VARCHAR(100);
ALTER TABLE Donations ALTER COLUMN donor TYPE VARCHAR(100);
ALTER TABLE Milestones ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE Milestones ALTER COLUMN campaignId TYPE VARCHAR(100);
ALTER TABLE UploadedFiles ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE UploadedFiles ALTER COLUMN uploader TYPE VARCHAR(100);